<?xml version="1.0"?>
<package format="3">
  <name>robocup_match_2d_simulation</name>
  <version>0.1.0</version>
  <description>2D simulator for robocup_realtime_monitoring with built-in web UI</description>

  <maintainer email="jeung158@hanyang.ac.kr">robocup_match_analyze_tools</maintainer>
  <license>Apache 2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>diagnostic_msgs</exec_depend>
  <exec_depend>robocup_msgs</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
